name: CI/CD MLflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  # Sesuaikan dengan lokasi dataset di dalam folder MLProject
  CSV_URL: "MLProject/gym_dataset_preprocessing.csv" 
  TARGET_VAR: "Experience_Level"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Tambahkan library yang dibutuhkan modelling.py agar --env-manager=local jalan
          pip install mlflow==2.19.0 pandas scikit-learn 

      - name: Run mlflow project
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          # Perubahan path: langsung merujuk ke folder MLProject/
          # -e merujuk pada entry point 'modelling.py' di file MLProject
          mlflow run MLProject/ -e modelling.py --env-manager=local --experiment-name gym_exp_project

      - name: Get latest MLflow run_id
        run: |
          # Perintah ini mencari folder terbaru di mlruns meskipun lokasinya dalam folder
          RUN_ID=$(find mlruns -type d -links 2 -printf '%T@ %p\n' | sort -n | tail -1 | awk '{print $2}' | cut -d'/' -f3)
          
          # Jika RUN_ID masih kosong, coba alternatif ls
          if [ -z "$RUN_ID" ]; then
            RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
          fi
          
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id detected: $RUN_ID"

      # Build Docker Model
      - name: Build Docker Model
        run: |
          # Pastikan formatnya runs:/$RUN_ID/model (hanya satu garis miring setelah titik dua)
          mlflow models build-docker --model-uri "runs:/${{ env.RUN_ID }}/model" --name "gym-exercise"
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          # Pastikan nama secret ini sama di GitHub Settings
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag Docker Image
        run: |
          docker tag cc ${{ secrets.DOCKERHUB_USERNAME }}/gym-exercise:latest

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/gym-exercise:latest
